//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.08 at 02:46:49 PM PDT 
//


package com.cloud.ucs.schema.listBlade;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cloud.ucs.schema.listBlade package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cloud.ucs.schema.listBlade
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConfigResolveDn }
     * 
     */
    public ConfigResolveDn createConfigResolveDn() {
        return new ConfigResolveDn();
    }

    /**
     * Create an instance of {@link ComputeBlade }
     * 
     */
    public ComputeBlade createComputeBlade() {
        return new ComputeBlade();
    }

    /**
     * Create an instance of {@link ConfigResolveDn.OutConfig }
     * 
     */
    public ConfigResolveDn.OutConfig createConfigResolveDnOutConfig() {
        return new ConfigResolveDn.OutConfig();
    }

}
