// Copyright 2012 Citrix Systems, Inc. Licensed under the
// Apache License, Version 2.0 (the "License"); you may not use this
// file except in compliance with the License.  Citrix Systems, Inc.
// reserves all rights not expressly granted by the License.
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// 
// Automatically generated by addcopyright.py at 04/03/2012
package com.cloud.network.as;

import java.util.Date;
import java.util.List;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.cloud.api.Identity;
import com.cloud.network.dao.FirewallRulesCidrsDaoImpl;
import com.cloud.utils.component.ComponentLocator;
import com.cloud.utils.db.GenericDao;
import com.cloud.utils.net.NetUtils;

@Entity
@Table(name="autoscale_vmgroups")
@Inheritance(strategy=InheritanceType.JOINED)
public class AutoScaleVmGroupVO implements AutoScaleVmGroup {

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id")
    long id;

    @Column(name="uuid")
    String uuid;

    @Column(name="zone_id", updatable=false)
    private long zoneId;

    @Column(name="domain_id", updatable=false)
    private long domainId;

    @Column(name="account_id")
    private long accountId;

    @Column(name = "load_balancer_id")
    private long loadBalancerId;

    @Column(name="min_members", updatable=true)
    private int minMembers;

    @Column(name="max_members", updatable=true)
    private int maxMembers;

    @Column(name = "profile_id")
    private long profileId;

    @Column(name=GenericDao.REMOVED_COLUMN)
    protected Date removed;

    @Column(name=GenericDao.CREATED_COLUMN)
    protected Date created;

    @Column(name = "revoke")
    private boolean revoke = false;

    @Column(name = "state")
    private String state;

	public AutoScaleVmGroupVO() {
    }

    public AutoScaleVmGroupVO( long lbRuleId, long zoneId, long domainId, long accountId, int minMembers, int maxMembers, long profileId) {
        this.uuid = UUID.randomUUID().toString();
        this.minMembers = minMembers;
        this.maxMembers = maxMembers;
        this.profileId = profileId;
        this.accountId = accountId;
        this.domainId = domainId;
        this.zoneId = zoneId;
    }

	@Override
    public String toString() {
        return new StringBuilder("AutoScaleVmGroupVO[").append("id").append("]").toString();
    }
	
    public long getId()    {
        return id;
    }
    
    public long getZoneId() {
    	return zoneId;
    }
    public long getDomainId() {
        return domainId;
    }
    public long getAccountId() {
        return accountId;
    }
    public long getLoadBalancerId() {
        return loadBalancerId;
    }

    public int getMinMembers() {
        return minMembers;
    }

    public int getMaxMembers() {
        return maxMembers;
    }

    public long getProfileId() {
        return profileId;
    }

    public Date getRemoved() {
        return removed;
    }

    public Date getCreated() {
        return created;
    }

    public boolean isRevoke() {
    	return false;
    }

    public void setRevoke(boolean revoke) {
        this.revoke = revoke;
    }

    public String getState() {
    	return "";
	}

	public void setState(String state) {
		this.state = state;
	}
}
