// Copyright 2012 Citrix Systems, Inc. Licensed under the
// Apache License, Version 2.0 (the "License"); you may not use this
// file except in compliance with the License.  Citrix Systems, Inc.
// reserves all rights not expressly granted by the License.
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Automatically generated by addcopyright.py at 04/03/2012


cloudStack.docs = {
  // Add volume
  helpVolumeName: {
    desc: 'Give the volume a unique name so you can find it later.',
    externalLink: 'http://abc.xyz/docs/...'
  },
  helpVolumeAvailabilityZone: {
    desc: 'Where do you want the storage to reside? This should be close to the VM that will use the volume.',
    externalLink: 'http://abc.xyz/docs/...'
  },
  helpVolumeDiskOffering: {
    desc: 'Choose the characteristics of the storage.',
    externalLink: 'http://abc.xyz/docs/...'
  },

  // Add network offering
  helpNetworkOfferingName: {
    desc: 'Any desired name for the network offering',
    externalLink: 'http://abc.xyz/docs/...'
  },
  helpNetworkOfferingNetworkRate: {
    desc: 'Allowed data transfer rate in MB per second',
    externalLink: 'http://abc.xyz/docs/...'
  },
  helpNetworkOfferingTrafficType: {
    desc: 'The type of network traffic that will be carried on the network',
    externalLink: 'http://abc.xyz/docs/...'
  },
  helpNetworkOfferingGuestType: {
    desc: 'Choose whether the guest network is isolated or shared.',
    externalLink: 'http://abc.xyz/docs/...'
  },
  helpNetworkOfferingSpecifyVLAN: {
    desc: '(Isolated guest networks only) Indicate whether a VLAN should be specified when this offering is used',
    externalLink: 'http://abc.xyz/docs/...'
  }
};

