//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.08 at 02:08:56 PM PDT 
//


package com.cloud.ucs.schema.listProfile;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="outDns">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="dn" type="{http://org.cloudstack/schema/cloudstack}Dn"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "outDns"
})
@XmlRootElement(name = "configFindDnsByClassId")
public class ConfigFindDnsByClassId {

    @XmlElement(required = true)
    protected ConfigFindDnsByClassId.OutDns outDns;

    /**
     * Gets the value of the outDns property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigFindDnsByClassId.OutDns }
     *     
     */
    public ConfigFindDnsByClassId.OutDns getOutDns() {
        return outDns;
    }

    /**
     * Sets the value of the outDns property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigFindDnsByClassId.OutDns }
     *     
     */
    public void setOutDns(ConfigFindDnsByClassId.OutDns value) {
        this.outDns = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="dn" type="{http://org.cloudstack/schema/cloudstack}Dn"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dn"
    })
    public static class OutDns {

        protected List<Dn> dn;

        /**
         * Gets the value of the dn property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dn property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDn().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Dn }
         * 
         * 
         */
        public List<Dn> getDn() {
            if (dn == null) {
                dn = new ArrayList<Dn>();
            }
            return this.dn;
        }

    }

}
