//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.08 at 02:08:56 PM PDT 
//


package com.cloud.ucs.schema.listProfile;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cloud.ucs.schema.listProfile package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cloud.ucs.schema.listProfile
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Dn }
     * 
     */
    public Dn createDn() {
        return new Dn();
    }

    /**
     * Create an instance of {@link ConfigFindDnsByClassId }
     * 
     */
    public ConfigFindDnsByClassId createConfigFindDnsByClassId() {
        return new ConfigFindDnsByClassId();
    }

    /**
     * Create an instance of {@link ConfigFindDnsByClassId.OutDns }
     * 
     */
    public ConfigFindDnsByClassId.OutDns createConfigFindDnsByClassIdOutDns() {
        return new ConfigFindDnsByClassId.OutDns();
    }

}
