//Copyright 2012 Citrix Systems, Inc. Licensed under the
//Apache License, Version 2.0 (the "License"); you may not use this
//file except in compliance with the License.  Citrix Systems, Inc.
//reserves all rights not expressly granted by the License.
//You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
//Automatically generated by addcopyright.py at 04/03/2012
package com.cloud.api.response;

import java.util.Date;
import java.util.List;

import com.cloud.api.ApiConstants;
import com.cloud.utils.IdentityProxy;
import com.cloud.serializer.Param;
import com.google.gson.annotations.SerializedName;

@SuppressWarnings("unused")
public class HostUpdatesResponse extends BaseResponse {
 @SerializedName(ApiConstants.ID) @Param(description="the id of the patch")
 private IdentityProxy id = new IdentityProxy("host_updates");

 @SerializedName(ApiConstants.HOST_UPDATE_LABEL) @Param(description="the label of the update")
 private String label;

 @SerializedName(ApiConstants.DESCRIPTION) @Param(description="description of the update")
 private String description;

 @SerializedName(ApiConstants.HOST_ID) @Param(description="host ID")
 private long hostId;

 @SerializedName(ApiConstants.AFTER_APPLY_GUIDANCE) @Param(description="guidance after applying the update")
 private String afterApplyGuidance;
 
 @SerializedName(ApiConstants.APPLIED) @Param(description="if the update has been applied or not")
 private Boolean applied;
 
 @SerializedName(ApiConstants.URL) @Param(description="URL of the availabel update")
 private String URL;

 @SerializedName(ApiConstants.TIMESTAMP) @Param(description="release time of the update")
 private String timestamp;

 
 public void setId(Long id) {
     this.id.setValue(id);
 }

 public void setLable(String label) {
     this.label = label;
 }
 
 public void setDescription(String description) {
     this.description = description;
 }

 public void setHostId(Long hostId) {
     this.hostId = hostId;
 }
 
 public void setAfterApplyGuidance(String afterApplyGuidance) {
     this.afterApplyGuidance = afterApplyGuidance;
 }
 
 public void setUpdateApplied(Boolean applied) {
     this.applied = applied;
 }
 
 public void setURL(String URL) {
     this.URL = URL;
 }
 
 public void setTimestamp(String timestamp) {
     this.timestamp = timestamp;
 }
}
