//Copyright 2012 Citrix Systems, Inc. Licensed under the
//Apache License, Version 2.0 (the "License"); you may not use this
//file except in compliance with the License.  Citrix Systems, Inc.
//reserves all rights not expressly granted by the License.
//You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
//Automatically generated by addcopyright.py at 04/03/2012
package com.cloud.api.response;

import com.cloud.api.ApiConstants;
import com.cloud.utils.IdentityProxy;
import com.cloud.serializer.Param;
import com.google.gson.annotations.SerializedName;

@SuppressWarnings("unused")
public class HostsWithPendingUpdatesResponse extends BaseResponse {
  @SerializedName(ApiConstants.ID) @Param(description="the id of the patch")
  private IdentityProxy id = new IdentityProxy("host_updates");
  
  @SerializedName(ApiConstants.UUID) @Param(description="the uuid of the host")
  private String uuid;
  @SerializedName(ApiConstants.NAME) @Param(description="the name of the host")
  private String name;

  public void setId(Long id) {
      this.id.setValue(id);
  }

  public void setUUID(String uuid) {
      this.uuid = uuid;
  }
  
  public void setName(String name) {
      this.name = name;
  }

}